### PR TITLE
(feat) U4X-731 : Allow clinicians to shift patients from one queue to another

### PR DESCRIPTION
**Pull request by jabahum**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

https://github.com/user-attachments/assets/1c4a0cee-3e2c-4a06-839b-e8dbf850d075

## Related Issue

https://metsprogramme.atlassian.net/browse/U4X-731

### CODE REVIEW

**Comment by slubwama** [comment]
@jabahum add video

**Comment by jabahum** [comment]
> @jabahum add video

noted

**Comment by Daphne210** [comment]
> > @jabahum add video
> 
> noted

@jabahum What's the difference between the pick button and that other action button now?

**Comment by NaseefMayanja** [comment]
> ## Requirements
> 
>     * [ ]  This PR has a title that briefly describes the work done including a [conventional commit](https://o3-docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.
> 
> 
> #### For changes to apps
> 
>     * [ ]   My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
> 
> 
> #### If applicable
> 
>     * [ ]  My work includes tests or is validated by existing tests.
> 
> 
> ## Summary
> ## Screenshots
> Screen.Recording.2024-10-16.at.11.49.00.mov
> ## Related Issue
> 
> https://metsprogramme.atlassian.net/browse/U4X-731
> ## Other

@jabahum shouldn't we only have one button of the two (bell and arrow)

**Comment by slubwama** [comment]
@akileng56  this requires your extra review

**Comment by slubwama** [comment]
@akileng56 how far with reviewing this feature.

**Comment by akileng56** [comment]
@slubwama @jabahum This does not solve the issue. Moving a patient from one clinician to another from the Triage point

**Review by akileng56 — APPROVED** [review]
Needs to be modified in the next PR

**Pull request merged**
